name: .NET Core

on:
  push:
    branches:
      - master 
      - 'feature/**'
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"
        echo "SemVer: $GITVERSION_PRERELEASETAG"
        echo "SemVer: $GITVERSION_MAJORMINORPATCH"
    - name: Package
      run: dotnet pack --no-restore --no-build --verbosity normal --output ./Packages -p:PackageVersion=$GITVERSION_MAJORMINORPATCH --version-suffix $GITVERSION_PRERELEASETAG
    - name: Display SemVer
      run: |
        cd Packages
        ls
